# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'EasyShopper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2.1'
  pod 'AlamofireImage', '~> 4.1.0'
  # Pods for EasyShopper

end
